### ISSUE TITLE
--greatest does not seem to work 

### ISSUE THREAD

**Issue by wind0r** [silverwind/updates#16]
I noticed when running updates against a project the newest release(date) gets used, but what i want is the newest version, so i switched to --greatest which somehow also wanted to downgrade a package.

How to reproduce:
Creating a new empty npm project and install electron (current version is 4.0.1 which is a month old) (newest patch 3.1.1 is a few days old) (https://www.npmjs.com/package/electron)

npx updates --greatest should not advise to downgrade the package.

just as a personal opinion. even without --greates updates should not advise to downgrade just because there is a new release for a older version

```
npx updates
npx: Installierte 107 in 6.28s
NAME        OLD       NEW       INFO
electron    ^4.0.1    ^3.1.1    https://github.com/electron/electron
```

```
npx updates --greatest
npx: Installierte 107 in 2.852s
NAME        OLD       NEW       INFO
electron    ^4.0.1    ^3.1.1    https://github.com/electron/electron
```

```
npx updates -g 
npx: Installierte 107 in 2.853s
NAME        OLD       NEW       INFO
electron    ^4.0.1    ^3.1.1    https://github.com/electron/electron
```

**Comment by wind0r** [comment]
found the bug. pr will be there soon :)

**Comment by silverwind** [comment]
Fixed by https://github.com/silverwind/updates/commit/aac7419deb46a74dab791a5153371dc02ddcc329, thanks!
