### ISSUE TITLE
Update readme with real update usage

### ISSUE THREAD

**Issue by DavidBabel** [silverwind/updates#22]
Hey there,

I like your plugin a looot.
I just wonder if this is the right way to do, if i want to update my dependencies ?
```bash
updates --update && yarn install
```
And if it is, it may be a good idea to add it to the readme.

Bye !

**Comment by silverwind** [comment]
Yes it is correct, first you updates package.json, then reinstall modules. I personally like to also remove node-nodules (thought it may be unnecessary), so you could do

```` bash
updates --update && rm -rf node_modules && yarn install
````
or even shorter :
```` bash
updates -u && rm -rf node_modules && yarn
````

**Comment by DavidBabel** [comment]
I wonder if their is a diference between th followings : 

_Supose we got a react out of date._

```bash
updates -u && yarn
```
and
```bash
yarn install react
```

Did you already experience if the result the same ? Including in yarn.lock ?
If it is, this plugin is a must have.
