### ISSUE TITLE
Fails with github package registry

### ISSUE THREAD

**Issue by aparajita** [silverwind/updates#25]
When the package registry is `https://npm.pkg.github.com`, it's failing at line 246. It seems the github registry does not support the same API as npm.

**Comment by silverwind** [comment]
I'm having a hard time getting any JSON response from their API. I just signed up for the beta, maybe I need to wait to be able to access the API? Does below command give you a different result, assuming you're in the beta?

```` bash
$ curl -sH "Accept: application/json" "https://npm.pkg.github.com/@codertocat%2fhello-world-npm"
Not Found%

**Comment by silverwind** [comment]
Actually, just got it working when sending a auth token, investigating.

**Comment by silverwind** [comment]
Should be fixed with `updates@8.1.1`.

**Comment by silverwind** [comment]
@aparajita please confirm if possible. I'm only 90% sure I implemented it correctly.

**Comment by aparajita** [comment]
Works like a charm, I and the countless others who will be using the github registry thank you!
