### ISSUE TITLE
request module should be a peerDependency

### ISSUE THREAD

**Issue by NetOperatorWibby** [silverwind/updates#3]
^ title

**Comment by silverwind** [comment]
I disagree. [`peerDependencies`](https://blog.domenic.me/peer-dependencies/) are meant for plugin-style relation between packages, which I just don't see here. If you use `request` in you project that uses `updates`, you **should** use your own version of `request`.

**Comment by NetOperatorWibby** [comment]
From the [`request-promise-native`](https://github.com/request/request-promise-native) repo:

> `request` is defined as a peer-dependency and thus has to be installed separately.

🤷🏾‍♂️

**Comment by silverwind** [comment]
It's a peer dependency to `request-promise-native`, not to consumers. But I think I may switch to another HTTP library to avoid headaches like this :)

**Comment by NetOperatorWibby** [comment]
Alright, I’ll close this then.

**Comment by silverwind** [comment]
At least you made me explore other options and I found a [faster](https://github.com/silverwind/updates/commit/e17cd64e7bfc428a954535e7eec83ef492ad6c93) http library in turn :)

**Comment by NetOperatorWibby** [comment]
Oh wow! Never heard of that package. Looks like I'll be using it too, haha!

**Comment by silverwind** [comment]
It's what npm uses internally, pretty nice and supports proxies too (which is a requirement for me).
