### ISSUE TITLE
Breaking changes in 9.0.0

### ISSUE THREAD

**Issue by Jameskmonger** [silverwind/updates#30]
Hi @silverwind 

Is there a list of breaking changes between 8.5.3 and 9.0.0?

I want to update but am worried about the breaking changes with the new major version

**Comment by silverwind** [comment]
The breaking change in 9.0.0 is a change in the format of `--json`, see https://github.com/silverwind/updates/commit/25c1db6b1a9a2f73281adac2ea45e4103bc318bb. If you haven't been using that argument, you're safe to upgrade.
