### ISSUE TITLE
Feature request: display release date

### ISSUE THREAD

**Issue by fisker** [silverwind/updates#40]
Registry response json has this info in `time` field on root.

1. for deps has updates, display the old/new version release date

This better be human friendly format.
Maybe additionally time diff of those two dates.

2. for deps without updates, display old version release date

---
Maybe like this

| NAME | OLD | NEW | INFO |
| :-- | :-- | :-- |  :-- |
|updates|1.0.0(29 days ago)|2.0.0(5 seconds ago)  |https://github.com/silverwind/updates|
|updates|1.0.0(29 days ago)|2.0.0(yesterday, 28 days since old version)  |https://github.com/silverwind/updates|
|updates|1.0.0(29 days ago)|-|https://github.com/silverwind/updates|

Problem: maybe too much info to display

---

Reason behind this request

- for new updates, I want see when it's released, maybe I'll skip the one too young.
- for deps without updates, if it has been a really long time since last release, maybe I'll assume it's already dead.

**Comment by silverwind** [comment]
Good suggestion. Not sure yet how to implement to keep the output compact. I'm thinking of a new column with just the release date of the new version.

**Comment by silverwind** [comment]
To keep it concise, I've only the age of the new version. I don't think the old version age is really relevant.

```
$ updates
NAME      OLD    NEW     AGE       INFO
p-map     3.0.0  4.0.0   3 days    https://github.com/sindresorhus/p-map
rrdir     4.0.0  5.0.0   11 days   https://github.com/silverwind/rrdir
eslint    6.7.2  6.8.0   3 months  https://github.com/eslint/eslint
rimraf    3.0.0  3.0.2   28 days   https://github.com/isaacs/rimraf
versions  7.0.5  8.2.3   1 day     https://github.com/silverwind/versions
iltorb    2.4.4  2.4.5   1 month   https://github.com/nstepien/iltorb

**Comment by fisker** [comment]
Great, thanks
