### ISSUE TITLE
Global installation

### ISSUE THREAD

**Issue by brettz9** [silverwind/updates#45]
Looks like a nice project!

However, a lot of times my interest is in performing updates for projects which, while being useful projects, don't tend to keep their own project very up to date. And some of these projects' developers are resistant to even `devDependencies` additions. If this package can be installed globally, I'd suggest mentioning it on the README so more may be willing to try it out, and if it can't be installed with the `-g` flag, I'd love to see this feature.

Also, as it seems the tool supports color output, I'd highly suggest putting a screenshot, as, color, besides being a selling point for attractiveness, ought to be helpful semantically (assuming `updates`' color support is implemented, as I imagine it would be, to use colors differentially based on semver).

**Comment by silverwind** [comment]
I personally prefer to keep all dependencies in `devDependencies` but it's worth mentioning the option of a global installation (works just fine).

**Comment by silverwind** [comment]
Done and screenshot added.

**Comment by brettz9** [comment]
Sorry--you said it'd be worth mentioning the global installation option, but I don't see it added. I do see the color screenshot though, which is cool, thank you...

**Comment by silverwind** [comment]
Oops, looks like I force-pushed over it accidentially, fixed now.
