### ISSUE TITLE
Shorthand

### ISSUE THREAD

**Issue by brettz9** [silverwind/updates#46]
I would suggest clarifying in the README that the first part of `&& rm -rf node_modules && npm i` is only necessary if you want to ensure your locally installed transitive dependencies and those in `package-lock.json` are also brought up to date.

While it's probably a generally good idea to do so, those on low speed connections or otherwise wishing to minimize time on updates, might not want to be forced to update those transitive dependencies when semver is still valid, unless perhaps there are vulnerabilities (e.g., as found by `npm audit`).

But if you are recommending it, you might want to add a flag which also handled this for the user. I use such updating frequently, and having to type all that extra text would be prohibitive to me. `rimraf` or `rimraf-promise` might be handy to implement if you were open to doing so. Just an idea.

**Comment by silverwind** [comment]
I will consider adding a `node_modules` removal using Node 12's recursive `rmdir`. But it's generally not that simple because for yarn v2, there's more work to be done.

I generally prefer the removal because I don't trust package managers enough but it's probably better to not recommend it.

**Comment by silverwind** [comment]
See https://github.com/silverwind/updates/issues/48 for node_modules removal. Docs currently don't recommend removal and that should be ok for most users.
