### ISSUE TITLE
Updating to dependency version that doesn't exist

### ISSUE THREAD

**Issue by NetOperatorWibby** [silverwind/updates#5]
<img width="273" alt="ss 2018-07-18 at 4 25 55 pm" src="https://user-images.githubusercontent.com/1288356/42905899-54aecaf2-8aa7-11e8-855f-95e0fa556425.png">

`turbocolor` recently updated to `2.3.3` not `3.0.0`. This also happened with the `relative-date` module but since that one is small enough I included it in my project wholesale.

**Comment by silverwind** [comment]
If you check [here](https://www.npmjs.com/package/turbocolor), `3.0.0` is actually published. The default mechanism is to update to the highest version available. You could use `--latest` option to instead go for the latest dist-tag instead.

**Comment by NetOperatorWibby** [comment]
When running my app after installing though, the module cannot be found. Also weird that the tagged version isn't the same as the max. That's not a problem with `updates` though, just people being weird.

I'll switch to using `--latest` though, thanks!

**Comment by silverwind** [comment]
> When running my app after installing though, the module cannot be found

Sounds like a bad publish by the author, but they cannot undo it now (unpublish only during the for 24hrs). I will do a few tests with `--latest`, as it seems that is the more safe way to go.

**Comment by silverwind** [comment]
Changed in v4.0.0 to prefer latest over greatest version.

**Comment by NetOperatorWibby** [comment]
<img width="251" alt="ss 2018-07-19 at 6 40 50 pm" src="https://user-images.githubusercontent.com/1288356/42973954-5beef83c-8b83-11e8-8705-92c9af837c1c.png">

Not sure if this is just my Terminal emulator but the right border isn't right. Didn't want to post an issue about this in case this is just something wrong with Hyper.

**Comment by silverwind** [comment]
Looks like your terminal renders emoji with less width, I'll fix that later.
