### ISSUE TITLE
Exclude updates by regex

### ISSUE THREAD

**Issue by yadickson** [silverwind/updates#57]
Hello,

When I use the update into de monorepo, is necessary to exclude all monorepo packages, the update fail because the monorepo dependencies is not found in npmjs.... So, is possible to fix the error exclude all packages....

updates -u -m -e @name/pack1,@name/pack2,@name/pack3,...

I want a options to exclude monorepo packages to use a regex, for example:

updates -u -m -e @name/*

Best regards

**Comment by silverwind** [comment]
Yes I think a `*` wildcard can be supported, given that it's likely a invalid dependency name everywhere.

**Comment by silverwind** [comment]
Regex should be possible as well in the config file, but for CLI, I would likely not support it and only support patterns.

**Comment by yadickson** [comment]
Thanks a lot @silverwind

**Comment by silverwind** [comment]
Actually it's `updates -u -m -e '/^@name//'`, e.g. regex pattern wrapped in `/`. That said, pattern support could be added as well separately.

**Comment by silverwind** [comment]
v14.5.0 now supports both glob and  regex, .e.g `updates -u -m -e '@name/*'` will now work as well.
