### ISSUE TITLE
Avoiding the error on `package.json` without dependencies

### ISSUE THREAD

**Issue by zloirock** [silverwind/updates#58]
If `package.json` does not contain any dependencies,`updates` throws `Error: No packages found`. I think it could be good to add an option to avoid this behavior or remove it at all. Why? The monorepo case. Not all packages from monorepos contain dependencies and something like `npx --workspaces updates` will throw an error.

**Comment by silverwind** [comment]
Agree, it should not throw an error, probably just complete with a small message.
