### ISSUE TITLE
Config files

### ISSUE THREAD

**Issue by zloirock** [silverwind/updates#59]
For example, I'm forced to maintain some projects with a big number of legacy dependencies that can't be updated. It's not very convenient to maintain lists of such dependencies in CLI args. Adding a config file like `.updatesrc` could be very useful.

**Comment by silverwind** [comment]
Yeah, a config file like `updates.config.yaml` might be something to consider. I personally have not needed it yet because I run it with `updates -e something` in a Makefile (or npm scripts).

**Comment by zloirock** [comment]
I'd prefer json since it's a native format for npm -> node -> js.

**Comment by silverwind** [comment]
I'd consider something like https://github.com/davidtheclark/cosmiconfig which supports many formats (probably too many).

**Comment by silverwind** [comment]
I think I will settle on a `updates.config.js` as the single config file. Maybe also typescript if the js engine in use can parse it (not node).

**Comment by silverwind** [comment]
[Config file](https://github.com/silverwind/updates#config-file) is available in [14.1.0](https://github.com/silverwind/updates/commit/c96f60f1626613482b0739691eb3fd619936b6e0).
