### ISSUE TITLE
It seems `undici` should be in `dependencies` instead of `devDependencies`

### ISSUE THREAD

**Issue by zloirock** [silverwind/updates#69]
![image](https://github.com/silverwind/updates/assets/2213682/a727b86f-249c-4406-918c-d5b07578b796)

**Comment by silverwind** [comment]
Ah, you are right, `fetch-enhanced` has it as `peerDependency` just to access the ProxyAgent, so it's meant to be carried as dependency. I'll move it.

**Comment by silverwind** [comment]
Fixed by reverting to `node-fetch`. undici is a too big of dependency to carry right now.

**Comment by silverwind** [comment]
Followup issue: https://github.com/silverwind/updates/issues/70
