### ISSUE TITLE
16.3.3 is broken

### ISSUE THREAD

**Issue by zloirock** [silverwind/updates#74]
<img width="946" alt="Снимок экрана 2024-07-28 в 02 55 49" src="https://github.com/user-attachments/assets/31d529aa-c934-459e-bf75-e8fc14a1b1cd">

**Comment by zloirock** [comment]
The same on CI: https://github.com/silverwind/updates/actions/runs/10124323589

**Comment by silverwind** [comment]
Sorry about that, local tests were passing, but only because the env var was set. I will look into publishing from actions so that this does not happen anymore.
