### ISSUE TITLE
Exit with error code

### ISSUE THREAD

**Issue by Kikobeats** [silverwind/updates#8]
Hello, 

I want to use the module for detecting package update in a release process.

The thing that I need if exit with an error code if a package need to be updated

The current behavior is:

```
❯ npx updates
npx: installed 103 in 3.324s
NAME     OLD       NEW
chalk    ~1.0.0    ~2.4.1

~/Projects/automatic-release master*
❯ echo $?
0
```

Just need something different to 0. Should be it the default behavior?

Other packages like [https://github.com/tjunnone/npm-check-updates](npm-check-updates) has a flag for do that:

```
-e, --error-level        set the error-level. 1: exits with error code 0 if no
                         errors occur. 2: exits with error code 0 if no
```

**Comment by silverwind** [comment]
Implemented with option `--exit-code` / `-E`. It uses exit code 2 to allow to distinguish from errors (exit code 1).

**Comment by silverwind** [comment]
Decided to rename the argument for clarity, it's not `--exit-on-outdated` / `-E`.
