### ISSUE TITLE
Allow limiting updates to latest minor/patch release

### ISSUE THREAD

**Issue by fhemberger** [silverwind/updates#9]
It would be nice if dependency updates could be limited to the latest minor or patch release. I'm looking for a way to auto-update dependencies without introducing possible breaking changes in semver major versions.

**Comment by silverwind** [comment]
Implemented `--semver patch|minor` option in 5.2.0.

**Comment by fhemberger** [comment]
Ohhh, you're awesome! Thank you! 😍

**Comment by silverwind** [comment]
Whoops, this was because of a last-minute change I did regarding the latest dist-tag, fixed now in 5.2.1.
